packages:
  - packages/*

catalog:
  "@arethetypeswrong/core": 0.18.2
  "@changesets/cli": 2.29.8
  "@playwright/test": 1.58.2
  "@pnpm/meta-updater": 2.0.6
  "@trivago/prettier-plugin-sort-imports": 6.0.2
  "@typescript/native-preview": 7.0.0-dev.20260218.1
  "@types/node": 24.10.13
  "@vitest/coverage-v8": 4.0.18
  "@vitest/expect": 4.0.18
  "cross-env": 10.1.0
  "eslint": 9.39.2
  "eslint-config-prettier": 10.1.8
  "eslint-plugin-unused-imports": 4.4.1
  "package-directory": 8.2.0
  "prettier": 3.8.1
  "publint": 0.3.17
  "tsdown": 0.20.3
  "turbo": 2.8.9
  "typescript-eslint": 8.54.0
  "vitest": 4.0.18
  "yaml": 2.8.2

overrides:
  "cross-spawn": ">=7.0.5"
  "glob": ">=10.5.0"
  "lodash": ">=4.17.23"
  "lodash-es": ">=4.17.23"
  "minimatch": ">=10.2.1"
  "tar": ">=7.5.8"

includeWorkspaceRoot: true

strictDepBuilds: true

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAge: 10080 # 1 week
minimumReleaseAgeExclude:
  - "minimatch@10.2.1"

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 40320 # 4 weeks
blockExoticSubdeps: true
