packages:
  - packages/*

catalog:
  "@biomejs/biome": 1.9.4
  "@changesets/cli": 2.29.4
  "@types/node": 22.15.29
  "@vitest/coverage-istanbul": 3.1.4
  "@vitest/expect": 3.1.4
  "tsup": 8.5.0
  "typescript": 5.8.3
  "vitest": 3.2.1

ignoredBuiltDependencies:
  - "@biomejs/biome"
  - esbuild
