packages:
  - packages/*

catalog:
  "@changesets/cli": 2.29.8
  "@playwright/test": 1.57.0
  "@types/node": 24.10.4
  "@vitest/coverage-v8": 4.0.16
  "@vitest/expect": 4.0.16
  "serve": 14.2.5
  "tsup": 8.5.1
  "typescript": 5.9.3
  "vitest": 4.0.16
  "yaml": 2.8.2
  "eslint": 9.39.2
  "typescript-eslint": 8.51.0
  "eslint-config-prettier": 10.1.8
  "eslint-plugin-unused-imports": 4.3.0
  "prettier": 3.7.4
  "@trivago/prettier-plugin-sort-imports": 6.0.1
  "turbo": 2.7.2
  "package-directory": 8.1.0
  "@pnpm/meta-updater": 2.0.6

overrides:
  "brace-expansion": ">=2.0.2"
  "cross-spawn": ">=7.0.5"
  "glob": ">=10.5.0"
  "js-yaml": ">=3.14.2"
  "vite": ">=6.4.1"

includeWorkspaceRoot: true

strictDepBuilds: true

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAge: 10080

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
