packages:
  - packages/*

catalog:
  "@changesets/cli": 2.29.7
  "@playwright/test": 1.56.1
  "@types/node": 24.10.4
  "@vitest/coverage-v8": 4.0.16
  "@vitest/expect": 4.0.16
  "serve": 14.2.5
  "tsup": 8.5.1
  "typescript": 5.9.3
  "vitest": 4.0.16
  "yaml": 2.8.2
  "eslint": 9.39.2
  "typescript-eslint": 8.50.1
  "eslint-config-prettier": 10.1.8
  "eslint-plugin-unused-imports": 4.3.0
  "prettier": 3.7.4
  "@trivago/prettier-plugin-sort-imports": 6.0.0
  "turbo": 2.6.1
  "package-directory": 8.1.0
  "@pnpm/meta-updater": 2.0.6

includeWorkspaceRoot: true

strictDepBuilds: true

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAge: 10080

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
