packages:
  - packages/*

catalog:
  "@changesets/cli": 2.29.7
  "@playwright/test": 1.56.1
  "@types/node": 22.19.0
  "@vitest/coverage-v8": 4.0.13
  "@vitest/expect": 4.0.13
  "serve": 14.2.5
  "tsup": 8.5.0
  "typescript": 5.9.3
  "vitest": 4.0.13
  "yaml": 2.8.1
  "eslint": 9.39.1
  "typescript-eslint": 8.46.3
  "eslint-config-prettier": 10.1.8
  "eslint-plugin-unused-imports": 4.3.0
  "prettier": 3.6.2
  "@trivago/prettier-plugin-sort-imports": 6.0.0
  "turbo": 2.6.0
  "package-directory": 8.1.0

includeWorkspaceRoot: true

strictDepBuilds: true

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAge: 1440
