packages:
  - packages/*

catalog:
  "@arethetypeswrong/core": 0.18.2
  "@changesets/cli": 2.30.0
  "@npm/types": 2.1.0
  "@playwright/test": 1.58.2
  "@pnpm/meta-updater": 2.0.6
  "@trivago/prettier-plugin-sort-imports": 6.0.2
  "@typescript/native-preview": 7.0.0-dev.20260323.1
  "@types/node": 24.12.0
  "@vitest/coverage-v8": 4.1.0
  "@vitest/expect": 4.1.0
  "cross-env": 10.1.0
  "eslint": 10.0.3
  "eslint-config-prettier": 10.1.8
  "eslint-plugin-check-file": 3.3.1
  "eslint-plugin-unused-imports": 4.4.1
  "markdown-table": 3.0.4
  "package-directory": 8.2.0
  "prettier": 3.8.1
  "publint": 0.3.18
  "tsdown": 0.21.3
  "turbo": 2.8.17
  "typescript-eslint": 8.57.0
  "vitepress": 1.6.4
  "vitest": 4.1.0
  "yaml": 2.8.2

overrides:
  "@types/node": "<=25"
  "cross-spawn": ">=7.0.5"
  "glob": ">=10.5.0"
  "lodash": ">=4.17.23"
  "lodash-es": ">=4.17.23"
  "minimatch": ">=10.2.3"
  "rollup": ">=4.59.0"
  "tar": ">=7.5.10"

includeWorkspaceRoot: true

strictDepBuilds: true

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAge: 10080 # 1 week
minimumReleaseAgeExclude:
  - "tar@7.5.11"

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 40320 # 4 weeks
blockExoticSubdeps: true
