packages:
  - packages/*

catalog:
  "@changesets/cli": 2.29.7
  "@playwright/test": 1.56.0
  "@types/node": 22.18.10
  "@vitest/coverage-istanbul": 3.2.4
  "@vitest/expect": 3.2.4
  "serve": 14.2.5
  "tsup": 8.5.0
  "typescript": 5.9.3
  "vitest": 3.2.4
  "yaml": 2.8.1
  "eslint": 9.37.0
  "typescript-eslint": 8.46.0
  "eslint-config-prettier": 10.1.8
  "eslint-plugin-unused-imports": 4.2.0
  "prettier": 3.6.2
  "@trivago/prettier-plugin-sort-imports": 5.2.2
  "turbo": 2.5.8
  "package-directory": 8.1.0

includeWorkspaceRoot: true

strictDepBuilds: true

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAge: 1440
