packages:
  - packages/*

catalog:
  "@changesets/cli": 2.29.8
  "@playwright/test": 1.58.2
  "@types/node": 24.10.13
  "@vitest/coverage-v8": 4.0.18
  "@vitest/expect": 4.0.18
  "tsdown": 0.20.3
  "typescript": 5.9.3
  "vitest": 4.0.18
  "yaml": 2.8.2
  "eslint": 10.0.1
  "typescript-eslint": 8.56.0
  "eslint-config-prettier": 10.1.8
  "eslint-plugin-unused-imports": 4.4.1
  "prettier": 3.8.1
  "@trivago/prettier-plugin-sort-imports": 6.0.2
  "turbo": 2.8.9
  "package-directory": 8.2.0
  "@pnpm/meta-updater": 2.0.6
  "cross-env": 10.1.0

overrides:
  "cross-spawn": ">=7.0.5"
  "glob": ">=10.5.0"
  "lodash": ">=4.17.23"
  "lodash-es": ">=4.17.23"
  "minimatch": ">=10.2.1"
  "tar": ">=7.5.8"

includeWorkspaceRoot: true

strictDepBuilds: true

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAge: 10080 # 1 week
minimumReleaseAgeExclude:
  - "minimatch@10.2.1"

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 40320 # 4 weeks
blockExoticSubdeps: true
