packages:
  - packages/*

catalog:
  "@biomejs/biome": 1.9.4
  "@changesets/cli": 2.29.3
  "@types/node": 22.15.3
  "@vitest/coverage-istanbul": 3.1.3
  "@vitest/expect": 3.1.3
  "tsup": 8.4.0
  "typescript": 5.8.3
  "vitest": 3.1.3

ignoredBuiltDependencies:
  - "@biomejs/biome"
  - esbuild
