packages:
  - packages/*

catalog:
  "@changesets/cli": 2.29.8
  "@playwright/test": 1.57.0
  "@types/node": 24.10.7
  "@vitest/coverage-v8": 4.0.17
  "@vitest/expect": 4.0.17
  "serve": 14.2.5
  "tsup": 8.5.1
  "typescript": 5.9.3
  "vitest": 4.0.17
  "yaml": 2.8.2
  "eslint": 9.39.2
  "typescript-eslint": 8.53.0
  "eslint-config-prettier": 10.1.8
  "eslint-plugin-unused-imports": 4.3.0
  "prettier": 3.7.4
  "@trivago/prettier-plugin-sort-imports": 6.0.2
  "turbo": 2.7.4
  "package-directory": 8.1.0
  "@pnpm/meta-updater": 2.0.6

overrides:
  "brace-expansion": ">=2.0.2"
  "cross-spawn": ">=7.0.5"
  "glob": ">=10.5.0"
  "js-yaml": ">=3.14.2"
  "tar": ">=7.5.3"
  "vite": ">=6.4.1"

includeWorkspaceRoot: true

strictDepBuilds: true

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAge: 10080 # 1 week
minimumReleaseAgeExclude:
  - "tar"

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 40320 # 4 weeks
blockExoticSubdeps: true
